CREATE TABLE IF NOT EXISTS vitrine_library (
    id VARCHAR(255) PRIMARY KEY,
    url LONGTEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    timestamp BIGINT NOT NULL,
    prompt TEXT,
    title VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);